### ISSUE TITLE
Add Open Graph Data To Events

### ISSUE THREAD

**Issue by CanopusFalling** [CanopusFalling/Queer-Calendar-Sheffield#20]

**Comment by jackcarey** [comment]
At the same time, rich result information may as well be considered: https://developers.google.com/search/docs/appearance/structured-data/event

**Comment by CanopusFalling** [comment]
> At the same time, rich result information may as well be considered:
> 
>     * Google: https://developers.google.com/search/docs/appearance/structured-data/event
> 
>     * Bing: https://www.bing.com/webmasters/help/?topicid=0f23328d

Brilliant suggestion, would go in a separate issue though. Can still be part of the same pr though.
