### ISSUE TITLE
Provide 'Add to other calendars' button

### ISSUE THREAD

**Issue by jackcarey** [CanopusFalling/Queer-Calendar-Sheffield#40]
The current 'Add to Google' button limits where users can add events. Consider using iCal to broaden this to Outlook, Apple, etc via  a new component.

- [adamgibbons/ics - npm](https://www.npmjs.com/package/ics)
- [Create ICS - Codepen](https://codepen.io/vlemoine/pen/MLwygX)

**Comment by CanopusFalling** [comment]
Currently implementing using ['add-to-calendar-button'](https://github.com/add2cal/add-to-calendar-button) module and the react wrapper. Check linked branch.
