### ISSUE TITLE
Event Card Descriptions Links Outside Card On Mobile

### ISSUE THREAD

**Issue by CanopusFalling** [CanopusFalling/Queer-Calendar-Sheffield#5]

**Comment by thezeeshann** [comment]
@CanopusFalling I would like to work on this issue assigned to me.

**Comment by CanopusFalling** [comment]
Sure thing! Feel free to submit a merge request to development when your done and ask for more details about this issue. I'll assign it to you now @thezeeshann

**Comment by thezeeshann** [comment]
@CanopusFalling I'm trying to run the project but got an error (Google API key is not defined) can you give me the API key?

**Comment by CanopusFalling** [comment]
@thezeeshann If you move to the development branch there are instructions for how to run the project in the README. These changes haven't been pushed to the main branch yet.

Here is the section about how to set up the key:

> - Create a copy of `.env.local.sample` and name it `.env.local`.
> - Replace `[Google-Calendar-API-Key]` with your google API key. The API key must have the calendar API enabled. [Instructions to obtain a Google API key.](https://support.google.com/googleapi/answer/6158862)

**Comment by thezeeshann** [comment]
@CanopusFalling I have fixed this issue.

**Comment by CanopusFalling** [comment]
@thezeeshann Amazing! If you want to submit a pull request into the development branch of this repository I'll review and merge those changes asap.

**Comment by thezeeshann** [comment]
@CanopusFalling okay great. I have tested this project it is working perfectly on all devices.

![Screenshot (175)](https://github.com/CanopusFalling/Queer-Calendar-Sheffield/assets/88139550/0a5e9a7a-f0f6-4e84-8059-f363b504bc37)
