### ISSUE TITLE
Fix Email Link

### ISSUE THREAD

**Issue by CanopusFalling** [CanopusFalling/Queer-Calendar-Sheffield#6]
Currently the email link in the site footer has the prefix 'email:' which is wrong and I must have been very tired while writing that. It actually needs to be 'mailto:' so that when clicked it opens the user's email client.

While fixing this, might be a good idea to add an email SVG icon next to the link.

**Comment by thezeeshann** [comment]
@CanopusFalling assign me this one also

**Comment by CanopusFalling** [comment]
@thezeeshann there's already a fix in #8 we're just waiting on the person who organises the calendar data to send me an image of themselves to merge that one.
