### ISSUE TITLE
Meet requirements for richer PWA install on Chrome

### ISSUE THREAD

**Issue by CanopusFalling** [CanopusFalling/Queer-Calendar-Sheffield#86]
Currently we do not meet the requirements for the richer install experience on chrome mobile or desktop, meeting these would allow for a much better experience for users on Chrome when installing the application as a progressive web application.

Docs here: https://developer.chrome.com/blog/richer-pwa-installation/

**Comment by JessFairbairn** [comment]
Ooh I should take a look at this

**Comment by CanopusFalling** [comment]
I can assign this issue to you if you'd like @JessFairbairn 
Lemme know if you need a hand getting the project set up.

**Comment by JessFairbairn** [comment]
Yes please!

**Comment by CanopusFalling** [comment]
All yours, good luck! I'm not free till next week but if you run into problems running the project locally or need any support reach out and I'll attempt to lend a hand, should have video call availability as of next week as well.
